In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [6]:
X_min = X.min() #Find the minimum vale of the Dataset
X_max = X.max() #Find the maximum value of the Dataset
X_scaled = (X - X_min) / (X_max - X_min + 1e-8) #Max-Min normalization Formula
                                                #(X - X_min) Shifts all values so minimum becomes 0
                                                #(X_max - X_min + 1e-8) Calculate the range of Data 
                                                # 1e-8 adds a tiny value to prevent division by Zero

In [7]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [9]:
model = keras.Sequential([    #Simple typ of NN where layers are connected one after another 
    layers.Input(shape= (X_train.shape[1],)),  #Input layer tells the model how many features each training sample has
    layers.Dense(8,activation= 'relu'),  #Creates a fully connected (Dense) layer (8)neurons ReLU Activation Function 
    layers.Dense(1,activation = 'sigmoid') # (1)neuron Sigmoid Activation(Binary Classification)
])

In [10]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])
#optimizer='sde'--> insted of the using the entire dataset, SGD uses one sample or mini-batch at a time
#loss = 'binary_crossentropy --> loss function the optimizer minimizes during training
#metrics=['accuracy'] -->  Monitors performance during training but doesn't affect weight updates

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4,verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.5751 - val_accuracy: 0.7500 - val_loss: 0.6102
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5761 - val_accuracy: 0.7500 - val_loss: 0.6096
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5746 - val_accuracy: 0.7500 - val_loss: 0.6090
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5741 - val_accuracy: 0.7500 - val_loss: 0.6085
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5735 - val_accuracy: 0.7500 - val_loss: 0.6079
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5726 - val_accuracy: 0.7500 - val_loss: 0.6073
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5733 - val_accuracy: 0.7500 - val_loss: 0.6068
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5722 - val_accuracy: 0.7500 - val_loss: 0.6062
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5711 - val_accuracy: 0.7500 - val_loss: 0.6056
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5713 - val_accuracy: 0.7500 - val_loss: 0.6050
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5701 - val_accuracy: 0.7500 - val_loss: 0.6044
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5699 - val_accuracy: 0.7500 - val_loss: 0.6038
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5716 - val_accuracy: 0.7500 - val_loss: 0.6033
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5686 - val_accuracy: 0.7500 - val_loss: 0.6027
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5686 - val_accuracy: 0.7500 - val_loss: 0.6021
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5681 - val_accuracy: 0.7500 - val_loss: 0.6015
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5680 - val_accuracy: 0.7500 - val_loss: 0.6009
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5669 - val_accuracy: 0.7500 - val_loss: 0.6003
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5660 - val_accuracy: 0.7500 - val_loss: 0.5997
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5677 - val_accuracy: 0.7500 - val_loss: 0.5991
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5663 - val_accuracy: 0.7500 - val_loss: 0.5985
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5645 - val_accuracy: 0.7500 - val_loss: 0.5979
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5647 - val_accuracy: 0.7500 - val_loss: 0.5973
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5662 - val_accuracy: 0.7500 - val_loss: 0.5967
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5634 - val_accuracy: 0.7500 - val_loss: 0.5961
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5625 - val_accuracy: 0.7500 - val_loss: 0.5955
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5625 - val_accuracy: 0.7500 - val_loss: 0.5949
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.5617 - val_accuracy: 0.7500 - val_loss: 0.5942
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5609 - val_accuracy: 0.7500 - val_loss: 0.5936
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5609 - val_accuracy: 0.7500 - val_loss: 0.5930
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5599 - val_accuracy: 0.7500 - val_loss: 0.5924
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5600 - val_accuracy: 0.7500 - val_loss: 0.5918
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5591 - val_accuracy: 0.7500 - val_loss: 0.5912
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5583 - val_accuracy: 0.7500 - val_loss: 0.5906
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5593 - val_accuracy: 0.7500 - val_loss: 0.5899
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5579 - val_accuracy: 0.7500 - val_loss: 0.5893
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5569 - val_accuracy: 0.7500 - val_loss: 0.5887
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5562 - val_accuracy: 0.7500 - val_loss: 0.5881
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5557 - val_accuracy: 0.7500 - val_loss: 0.5875
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5560 - val_accuracy: 0.7500 - val_loss: 0.5868
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5550 - val_accuracy: 0.7500 - val_loss: 0.5862
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5549 - val_accuracy: 0.7500 - val_loss: 0.5856
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5537 - val_accuracy: 0.7500 - val_loss: 0.5849
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5538 - val_accuracy: 0.7500 - val_loss: 0.5843
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5529 - val_accuracy: 0.7500 - val_loss: 0.5837
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5525 - val_accuracy: 0.7500 - val_loss: 0.5830
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5515 - val_accuracy: 0.7500 - val_loss: 0.5824
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5522 - val_accuracy: 0.7500 - val_loss: 0.5818
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5505 - val_accuracy: 0.7500 - val_loss: 0.5811
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5502 - val_accuracy: 0.7500 - val_loss: 0.5805
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5502 - val_accuracy: 0.7500 - val_loss: 0.5798
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5489 - val_accuracy: 0.7500 - val_loss: 0.5792
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5482 - val_accuracy: 1.0000 - val_loss: 0.5785
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5483 - val_accuracy: 1.0000 - val_loss: 0.5779
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5472 - val_accuracy: 1.0000 - val_loss: 0.5773
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5472 - val_accuracy: 1.0000 - val_loss: 0.5766
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5472 - val_accuracy: 1.0000 - val_loss: 0.5759
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5466 - val_accuracy: 1.0000 - val_loss: 0.5753
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5451 - val_accuracy: 1.0000 - val_loss: 0.5746
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5446 - val_accuracy: 1.0000 - val_loss: 0.5740
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7500 - loss: 0.5457 - val_accuracy: 1.0000 - val_loss: 0.5734
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5434 - val_accuracy: 1.0000 - val_loss: 0.5727
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5435 - val_accuracy: 1.0000 - val_loss: 0.5720
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5435 - val_accuracy: 1.0000 - val_loss: 0.5714
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.5419 - val_accuracy: 1.0000 - val_loss: 0.5707
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.5413 - val_accuracy: 1.0000 - val_loss: 0.5700
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5408 - val_accuracy: 1.0000 - val_loss: 0.5694
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.5403 - val_accuracy: 1.0000 - val_loss: 0.5687
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5399 - val_accuracy: 1.0000 - val_loss: 0.5681
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5391 - val_accuracy: 1.0000 - val_loss: 0.5674
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5394 - val_accuracy: 1.0000 - val_loss: 0.5667
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5392 - val_accuracy: 1.0000 - val_loss: 0.5660
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5387 - val_accuracy: 1.0000 - val_loss: 0.5654
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8333 - loss: 0.5369 - val_accuracy: 1.0000 - val_loss: 0.5647
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5371 - val_accuracy: 1.0000 - val_loss: 0.5640
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5362 - val_accuracy: 1.0000 - val_loss: 0.5633
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5358 - val_accuracy: 1.0000 - val_loss: 0.5627
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5354 - val_accuracy: 1.0000 - val_loss: 0.5620
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5350 - val_accuracy: 1.0000 - val_loss: 0.5613
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8333 - loss: 0.5342 - val_accuracy: 1.0000 - val_loss: 0.5606
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5331 - val_accuracy: 1.0000 - val_loss: 0.5600
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5333 - val_accuracy: 1.0000 - val_loss: 0.5593
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5325 - val_accuracy: 1.0000 - val_loss: 0.5586
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5323 - val_accuracy: 1.0000 - val_loss: 0.5579
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5340 - val_accuracy: 1.0000 - val_loss: 0.5572
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5311 - val_accuracy: 1.0000 - val_loss: 0.5566
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5301 - val_accuracy: 1.0000 - val_loss: 0.5559
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5300 - val_accuracy: 1.0000 - val_loss: 0.5552
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5288 - val_accuracy: 1.0000 - val_loss: 0.5545
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5288 - val_accuracy: 1.0000 - val_loss: 0.5538
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5277 - val_accuracy: 1.0000 - val_loss: 0.5531
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5280 - val_accuracy: 1.0000 - val_loss: 0.5524
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5287 - val_accuracy: 1.0000 - val_loss: 0.5517
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5263 - val_accuracy: 1.0000 - val_loss: 0.5510
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8333 - loss: 0.5255 - val_accuracy: 1.0000 - val_loss: 0.5503
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8333 - loss: 0.5250 - val_accuracy: 1.0000 - val_loss: 0.5496
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5243 - val_accuracy: 1.0000 - val_loss: 0.5489
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8333 - loss: 0.5249 - val_accuracy: 1.0000 - val_loss: 0.5482
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8333 - loss: 0.5243 - val_accuracy: 1.0000 - val_loss: 0.5475
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5248 - val_accuracy: 1.0000 - val_loss: 0.5468